/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package medialib;

import java.util.List;
import java.util.Scanner;

import org.checkerframework.checker.units.qual.s;

import utils.Parser;
import utils.Writer;

import utils.Entities.Admin;
import utils.Entities.User;
import utils.Entities.Book;


public class App {
  private static List<Admin> admins;
  private static List<User> users;
  private static List<Book> books;

  public static void initialize() {
    Parser parser = new Parser();

    parser.parse();

    admins = parser.getAdmins();
    users = parser.getUsers();
    books = parser.getBooks();
  }

  public void finalize() {
    Writer.write(users, books);
  }

  public String getGreeting() {
    return "\n\n\nHello World!\n\n\n";
  }

  public static void printAdmins() {
    System.out.println("-----------------Admins-----------------");
    for (Admin admin : admins) {
      System.out.println(admin.getUsername());
    }
  }
  public static void printUsers() {
    System.out.println("-----------------Users------------------");
    for (User user : users) {
      System.out.println(user.getUsername());
    }
  }
  public static void printBooks() {
    System.out.println("-----------------Books------------------");
    for (Book book : books) {
      System.out.println(book.getTitle());
    }
  }
  public static void printAll() {
    printAdmins();
    printUsers();
    printBooks();
  }

  public static void randomize() {
    Writer.populate();
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());

    App app = new App();

    if(false) {
      app.randomize();
    }

    app.initialize();
    app.printAll();
    System.out.println("\n\n\n");

    /* //example db usage
    User darcie = getUserByUsername("darcie.bernhard");
    darcie.setFirstName("Darcie");
    darcie.setLastName("Bernhard"); */

    // Login prompt
    User user;
    while((user = app.promptLogin()) == null) {
      System.out.println("Please try again");
    }
    System.out.println("Welcome " + user.getFirstName() + " " + user.getLastName());

    app.finalize();
  }


  public static User getUserByUsername(String username) {
    for (User user : users) {
      if (user.getUsername().equals(username)) {
        return user;
      }
    }
    return null; // User not found
  }

  public User promptLogin() {
    Scanner scanner = new Scanner(System.in);

    System.out.println("Username: ");
    String username = scanner.nextLine();
    // String username = System.console().readLine();

    System.out.println("Password: ");
    String password = scanner.nextLine();
    // String password = System.console().readLine();
    
    scanner.close();

    User user = getUserByUsername(username);
    if(user == null) {
      System.out.println("User not found");
      return null;
    }

    if(!user.getPassword().equals(password)) {
      System.out.println("Incorrect password");
      return null;
    }

    return user;
  }
}
